# Generated by Django 4.0.3 on 2022-09-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=80)),
                ('distance', models.IntegerField()),
                ('time', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
            ],
        ),
    ]
