# Generated by Django 4.0.3 on 2022-09-18 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs_app', '0002_remove_run_time_run_duration_alter_run_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
