# Generated by Django 4.0.3 on 2022-11-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('event_home_url', models.URLField()),
                ('event_registration_url', models.URLField()),
            ],
        ),
    ]
